//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialStatement
    {
        public int Id { get; set; }
        public int InstallmentCount { get; set; }
        public int OrderOfInstallment { get; set; }
        public double Amount { get; set; }
        public System.DateTime Date { get; set; }
        public bool PaymentStatus { get; set; }
        public bool IsPaymentInAdvance { get; set; }
        public int StudentId { get; set; }
        public int ClassId { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Student Student { get; set; }
    }
}
