//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchool.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LanguageAcademyEntities : DbContext
    {
        public LanguageAcademyEntities()
            : base("name=LanguageAcademyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<BusTransportation> BusTransportations { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Class_Students> Class_Students { get; set; }
        public virtual DbSet<Class_WeekDay> Class_WeekDay { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<FinancialStatement> FinancialStatements { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<SocialOpportunity> SocialOpportunities { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<WeekDay> WeekDays { get; set; }
    }
}
