//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace LanguageSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int Id { get; set; }
        
        [Required]
        public string Position { get; set; }
        [Required(ErrorMessage = "İsminizi giriniz.")]
        public string Firstname { get; set; }
        [Required(ErrorMessage = "Soyisminizi giriniz.")]
        public string Lastname { get; set; }
        [Required(ErrorMessage = "Email adresinizi giriniz.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Telefon numaranızı giriniz.")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Şifrenizi giriniz.")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Kullanıcı adınızı giriniz.")]
        public string Username { get; set; }
    }
}
